train:
  epochs: 100000
  batch_size: 16
  lr: 0.0001
  uniformity_loss_weight: 1 
  mask_ratio: 0.3
  train_split: 0.7
  lambda_recon: 1.0
  lambda_obstacle: 1.0
  accumulation_steps: 16
  resume: true
  checkpoint_path: "./outputs/best_model_checkpoint.pth"
data:
  event_dir: "/home/sas/backup/data/data/event"
  resize: [640, 480]
logging:
  output_dir: "outputs"
  tensorboard_log_dir: "outputs/logs"
